services:
  nginx:
    image: nginx:alpine
    container_name: nginx_lab3
    ports:
      - "8082:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:8-fpm-alpine
    container_name: php_lab3
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000" 
